---
- hosts: all
  gather_facts: true
  become: true

  tasks:
    - block:
        - name: Acquire lock
          include_role:
            name: ansible_lockfile_role
          vars:
            lock_path: /tmp/test.lock  # This defaults to /tmp/ansible.lock

        - name: Do some work
          ansible.builtin.command: echo "hello world from $(hostname)"
          register: hello
          changed_when: false

        - ansible.builtin.debug:
            var: hello.stdout

      always:
        - name: Release lock
          include_role:
            name: ansible_lockfile_role
            tasks_from: release.yml
          vars:
            lock_path: /tmp/test.lock
