---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    container_name: instance
    image: ubuntu:22.04
    command: /bin/bash -lc "sleep infinity"

  tasks:
    - name: Pull image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Create container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        command: "{{ command }}"
        detach: true
        tty: true
