---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    container_name: instance

  tasks:
    - name: Remove container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true
