---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Install python3 for Ansible modules
      ansible.builtin.raw: |
        apt-get update -y && apt-get install -y python3
      changed_when: false
